# Generated by Django 4.0.3 on 2022-04-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_actor_fullscore_alter_instrument_score_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='duration',
            field=models.IntegerField(default=6),
        ),
    ]
