# Generated by Django 4.0.3 on 2022-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=16)),
                ('score_data', models.TextField()),
                ('measure', models.IntegerField()),
            ],
        ),
    ]
