# Generated by Django 4.0.3 on 2022-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_actor_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
